NONE = 'O'
PAD = "[PAD]"
UNK = "[UNK]"

# for BERT
CLS = '[CLS]'
SEP = '[SEP]'

# 34 event triggers
TRIGGERS = ['Business:Merge-Org',
            'Business:Start-Org',
            'Business:Declare-Bankruptcy',
            'Business:End-Org',
            'Justice:Pardon',
            'Justice:Extradite',
            'Justice:Execute',
            'Justice:Fine',
            'Justice:Trial-Hearing',
            'Justice:Sentence',
            'Justice:Appeal',
            'Justice:Convict',
            'Justice:Sue',
            'Justice:Release-Parole',
            'Justice:Arrest-Jail',
            'Justice:Charge-Indict',
            'Justice:Acquit',
            'Conflict:Demonstrate',
            'Conflict:Attack',
            'Contact:Phone-Write',
            'Contact:Meet',
            'Personnel:Start-Position',
            'Personnel:Elect',
            'Personnel:End-Position',
            'Personnel:Nominate',
            'Transaction:Transfer-Ownership',
            'Transaction:Transfer-Money',
            'Life:Marry',
            'Life:Divorce',
            'Life:Be-Born',
            'Life:Die',
            'Life:Injure',
            'Movement:Transport']

"""
    28 argument roles
    
    There are 35 roles in ACE2005 dataset, but the time-related 8 roles were replaced by 'Time' as the previous work (Yang et al., 2016).
    ['Time-At-End','Time-Before','Time-At-Beginning','Time-Ending', 'Time-Holds', 'Time-After','Time-Starting', 'Time-Within'] --> 'Time'.
"""
ARGUMENTS = ['Place',
             'Crime',
             'Prosecutor',
             'Sentence',
             'Org',
             'Seller',
             'Entity',
             'Agent',
             'Recipient',
             'Target',
             'Defendant',
             'Plaintiff',
             'Origin',
             'Artifact',
             'Giver',
             'Position',
             'Instrument',
             'Money',
             'Destination',
             'Buyer',
             'Beneficiary',
             'Attacker',
             'Adjudicator',
             'Person',
             'Victim',
             'Price',
             'Vehicle',
             'Time']

# 25 SRL tags
SRL_ARGUMENTS =   ['V',
                   'ARG0',
                   'ARG1',
                   'ARG2',
                   'ARG3',
                   'ARG4',
                   'ARG5',
                   'ARGM-ADJ',
                   'ARGM-ADV',
                   'ARGM-CAU',
                   'ARGM-COM',
                   'ARGM-DIR',
                   'ARGM-DIS',
                   'ARGM-EXT',
                   'ARGM-GOL',
                   'ARGM-LOC',
                   'ARGM-LVB',
                   'ARGM-MNR',
                   'ARGM-MOD',
                   'ARGM-NEG',
                   'ARGM-PNC',
                   'ARGM-PRD',
                   'ARGM-PRP',
                   'ARGM-REC',
                   'ARGM-TMP']

# 54 entities
ENTITIES = ['VEH:Water',
            'GPE:Nation',
            'ORG:Commercial',
            'GPE:State-or-Province',
            'Contact-Info:E-Mail',
            'Crime',
            'ORG:Non-Governmental',
            'Contact-Info:URL',
            'Sentence',
            'ORG:Religious',
            'VEH:Underspecified',
            'WEA:Projectile',
            'FAC:Building-Grounds',
            'PER:Group',
            'WEA:Exploding',
            'WEA:Biological',
            'Contact-Info:Phone-Number',
            'WEA:Chemical',
            'LOC:Land-Region-Natural',
            'WEA:Nuclear',
            'LOC:Region-General',
            'PER:Individual',
            'WEA:Sharp',
            'ORG:Sports',
            'ORG:Government',
            'ORG:Media',
            'LOC:Address',
            'WEA:Shooting',
            'LOC:Water-Body',
            'LOC:Boundary',
            'GPE:Population-Center',
            'GPE:Special',
            'LOC:Celestial',
            'FAC:Subarea-Facility',
            'PER:Indeterminate',
            'VEH:Subarea-Vehicle',
            'WEA:Blunt',
            'VEH:Land',
            'TIM:time',
            'Numeric:Money',
            'FAC:Airport',
            'GPE:GPE-Cluster',
            'ORG:Educational',
            'Job-Title',
            'GPE:County-or-District',
            'ORG:Entertainment',
            'Numeric:Percent',
            'LOC:Region-International',
            'WEA:Underspecified',
            'VEH:Air',
            'FAC:Path',
            'ORG:Medical-Science',
            'FAC:Plant',
            'GPE:Continent']

# 45 pos tags
POSTAGS = ['VBZ', 'NNS', 'JJR', 'VB', 'RBR',
           'WP', 'NNP', 'RP', 'RBS', 'VBP',
           'IN', 'UH', 'JJS', 'NNPS', 'PRP$',
           'MD', 'DT', 'WP$', 'POS', 'LS',
           'CC', 'VBN', 'EX', 'NN', 'VBG',
           'SYM', 'FW', 'TO', 'JJ', 'VBD',
           'WRB', 'CD', 'PDT', 'WDT', 'PRP',
           'RB', ',', '``', "''", ':',
           '.', '$', '#', '-LRB-', '-RRB-']

# Event Schema

EVENT_SCHEMA =  {'Business:Declare-Bankruptcy': ['Org', 'Time', 'Place'],
 'Business:End-Org': ['Place', 'Org', 'Time'],
 'Business:Merge-Org': ['Org', 'Time'],
 'Business:Start-Org': ['Org', 'Agent', 'Place', 'Time'],
 'Conflict:Attack': ['Attacker',
  'Place',
  'Target',
  'Time',
  'Instrument',
  'Victim',
  'Agent'],
 'Conflict:Demonstrate': ['Place', 'Entity', 'Time'],
 'Contact:Meet': ['Place', 'Entity', 'Time'],
 'Contact:Phone-Write': ['Entity', 'Time', 'Place'],
 'Justice:Acquit': ['Defendant', 'Adjudicator', 'Crime', 'Time'],
 'Justice:Appeal': ['Adjudicator', 'Plaintiff', 'Place', 'Crime', 'Time'],
 'Justice:Arrest-Jail': ['Person', 'Agent', 'Time', 'Place', 'Crime'],
 'Justice:Charge-Indict': ['Adjudicator',
  'Defendant',
  'Crime',
  'Prosecutor',
  'Time',
  'Place'],
 'Justice:Convict': ['Defendant', 'Adjudicator', 'Crime', 'Place', 'Time'],
 'Justice:Execute': ['Agent', 'Place', 'Person', 'Time', 'Crime'],
 'Justice:Extradite': ['Destination', 'Origin', 'Person', 'Agent', 'Time'],
 'Justice:Fine': ['Entity', 'Money', 'Crime', 'Adjudicator', 'Place', 'Time'],
 'Justice:Pardon': ['Defendant', 'Adjudicator', 'Place', 'Time'],
 'Justice:Release-Parole': ['Person', 'Entity', 'Time', 'Place', 'Crime'],
 'Justice:Sentence': ['Adjudicator',
  'Defendant',
  'Sentence',
  'Crime',
  'Place',
  'Time'],
 'Justice:Sue': ['Plaintiff',
  'Defendant',
  'Crime',
  'Adjudicator',
  'Place',
  'Time'],
 'Justice:Trial-Hearing': ['Defendant',
  'Crime',
  'Adjudicator',
  'Prosecutor',
  'Place',
  'Time'],
 'Life:Be-Born': ['Place', 'Person', 'Time'],
 'Life:Die': ['Victim', 'Agent', 'Place', 'Time', 'Instrument', 'Person'],
 'Life:Divorce': ['Person', 'Time', 'Place'],
 'Life:Injure': ['Victim', 'Agent', 'Place', 'Time', 'Instrument'],
 'Life:Marry': ['Person', 'Time', 'Place'],
 'Movement:Transport': ['Vehicle',
  'Artifact',
  'Destination',
  'Agent',
  'Time',
  'Origin',
  'Victim',
  'Place'],
 'Personnel:Elect': ['Person', 'Position', 'Entity', 'Place', 'Time'],
 'Personnel:End-Position': ['Person', 'Entity', 'Position', 'Time', 'Place'],
 'Personnel:Nominate': ['Person', 'Agent', 'Time', 'Position'],
 'Personnel:Start-Position': ['Person', 'Entity', 'Position', 'Place', 'Time'],
 'Transaction:Transfer-Money': ['Giver',
  'Recipient',
  'Money',
  'Beneficiary',
  'Time',
  'Place'],
 'Transaction:Transfer-Ownership': ['Artifact',
  'Buyer',
  'Seller',
  'Time',
  'Place',
  'Beneficiary',
  'Price']}